version: "3"

services:
  api01: &api
    build:
      context: .
      args:
        - NODE_NAME=diogenes
    container_name: api01
    hostname: api01
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_NAME=diogenes
    depends_on:
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'

  api02:
    <<: *api
    # build:
    #   context: .
    #   args:
    #     - NODE_NAME=alexander
    container_name: api02
    hostname: api02
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    depends_on: []
    environment:
      - NODE_NAME=alexander

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '100MB'
