version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_NAME=diogenes
    # depends_on:
    #   - db
