version: "3"
# Ref https://github.com/oliveigah/rinha_backend/blob/master/docker-compose.yml
services:
  api01: &api
    build:
      context: .
      args:
        - NODE_NAME=diogenes
    container_name: api01
    hostname: api01
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_NAME=diogenes
      - NODE_TYPE=master
      - BOOTSTRAP_NODES=alexander@api02
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_NAME=alexander
      - BOOTSTRAP_NODES=diogenes@api01

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '100MB'
